测试data内容

In [2]:
import scipy.io as scp

In [3]:
trainset=scp.loadmat('data/TrainSet.mat')
validset=scp.loadmat('data/ValSet.mat')
testset=scp.loadmat('data/TestSet.mat')

In [4]:
# print(trainset)
print(type(trainset))
print(len(trainset))
print(trainset.keys())
print(trainset['__header__'])

<class 'dict'>
5
dict_keys(['__header__', '__version__', '__globals__', 'tracks', 'traj'])
b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sun Oct 10 16:12:44 2021'


In [11]:
print(type(trainset['traj']))
print(type(trainset['tracks']))
print('trainset"s traj shape: ',trainset['traj'].shape)
print('trainset"s tracks shape: ',trainset['tracks'].shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
trainset"s traj shape:  (5922867, 47)
trainset"s tracks shape:  (6, 2356)


In [4]:
train_tracks=trainset['tracks']
valid_tracks=validset['tracks']
test_tracks=testset['tracks']
# print(tracks)
# print(type(tracks))
print('train_tracks shape：',train_tracks.shape)
print('valid_tracks shape:',valid_tracks.shape)
print('test_tracks shape:',test_tracks.shape)

train_tracks shape： (6, 2356)
valid_tracks shape: (6, 2499)
test_tracks shape: (6, 3366)


In [6]:
print(train_tracks[0,2355])

IndexError: index 2356 is out of bounds for axis 1 with size 2356

In [31]:
print(type(train_tracks[0][820]),'\n')
print(train_tracks[0][820],'\n')
print(train_tracks[3].shape,'\n')

<class 'numpy.ndarray'> 

[[1953.    1954.    1955.    ... 2419.    2420.    2421.   ]
 [  38.953   38.936   38.917 ...   32.171   32.166   32.161]
 [  35.609   39.109   42.609 ... 2112.58  2119.08  2125.08 ]
 [   4.       4.       4.    ...    3.       3.       3.   ]] 

(2356,) 



In [13]:
train_traj=trainset['traj']
valid_traj=validset['traj']
test_traj=testset['traj']
# print(traj)
# print(type(traj))
print('train traj shape: ',train_traj.shape)
print('valid traj shape: ',valid_traj.shape)
print('test traj shape: ',test_traj.shape)


train traj shape:  (5922867, 47)
valid traj shape:  (859769, 47)
test traj shape:  (1505756, 47)
[  1.      2.     43.     16.724 148.784   2.      1.      1.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.     13.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.   ]


In [35]:
print(train_traj[9950])

[1.000000e+00 4.000000e+01 4.000000e+02 3.176100e+01 1.517488e+03
 3.000000e+00 1.000000e+00 1.000000e+00 0.000000e+00 0.000000e+00
 0.000000e+00 0.000000e+00 0.000000e+00 3.200000e+01 0.000000e+00
 0.000000e+00 0.000000e+00 0.000000e+00 2.600000e+01 0.000000e+00
 0.000000e+00 0.000000e+00 4.400000e+01 0.000000e+00 0.000000e+00
 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
 0.000000e+00 2.500000e+01 0.000000e+00 0.000000e+00 0.000000e+00
 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
 2.100000e+01 0.000000e+00]


In [70]:
import numpy as np
a=np.array([[1,2,3],[2,3,4]])
# a.shape
a

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
import torch
a=torch.tensor([[1.1,2.2,3.3],[0,0,0]])
print(a)
c=a.permute(1,0)
print(c)
b=torch.zeros_like(a).float()
print(b)
b=b.masked_scatter_(b,a)
print(b)

tensor([[1.1000, 2.2000, 3.3000],
        [0.0000, 0.0000, 0.0000]])
tensor([[1.1000, 0.0000],
        [2.2000, 0.0000],
        [3.3000, 0.0000]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
import time
import torch
import os
file_time=time.strftime('%Y-%m-%d-%H-%M-%S')
print(file_time)
# print(os.path.join())
if not os.path.isdir('./models'):
    os.mkdir('./models')
model_path=os.path.join('models',file_time,'.csv')
a=torch.tensor([[1.1,2.2,3.3],[0,0,0]])
torch.save(a,model_path)

print(model_path)


2022-12-05-16-19-18


RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\caffe2\serialize\inline_container.cc:354] . invalid file name: models\2022-12-05-16-19-18\.csv

In [8]:
import torch
a=torch.tensor([[1,2],[3,4]])
b=len(a)
print(b)

2


In [3]:
import os
import time
file_time=time.strftime('%Y-%m-%d-%H-%M-%S')
if not os.path.isdir('./models'):
    os.mkdir('./models')
model_path='models/cslstm_m_'+file_time+'.ckpt' 
model_path

'models/cslstm_m_2022-12-06-19-02-27.ckpt'

In [2]:
import math
a=math.e
print(math.log(a))

1.0


2023.1.15

In [7]:
import numpy as np

In [8]:
a=np.zeros(2)
b=np.zeros([2])
print(a)
print(b)

[0. 0.]
[0. 0.]


In [19]:
a=np.eye(2)[1].astype(int)

array([0, 1])

In [54]:
a=np.eye(4)
print(np.where(a[:,0]==0))
print((np.argwhere(a[:,0]==0)).shape())
print(a.size)
print(a.shape)

(array([1, 2, 3], dtype=int64),)


TypeError: 'tuple' object is not callable

In [60]:
a=np.array([[2,2]])
print(a)
print(a.shape)

[[2 2]]
(1, 2)


In [64]:
def make():
    return  1,2,3,4,5
print(make())
print(len(make()))

(1, 2, 3, 4, 5)
5


In [82]:
import torch
a=torch.zeros(2,3,2,3).byte()
a.type()

'torch.ByteTensor'

In [96]:
a=torch.ones(2).byte()
# a=torch.tensor([1,2])
a.dtype

torch.float32

In [1]:
import torch

In [4]:
a=torch.ones(2,4,5)
a=a.view(-1,5)
print(a.shape)

torch.Size([8, 5])


In [32]:
a=torch.ones(3,2).byte()
b=torch.Tensor([[1,2],[3,4]])
c=torch.cat((a,b),dim=0)
d=c.repeat(2,1,1)
d.shape

torch.Size([2, 5, 2])

In [47]:
print(b[:,1:2],b[:,1:2].shape)
print(b[:,1],b[:,1].shape)

tensor([[2.],
        [4.]]) torch.Size([2, 1])
tensor([2., 4.]) torch.Size([2])


In [1]:
import torch

In [4]:

def logsumexp(inputs, dim=None, keepdim=False):
    if dim is None:
        inputs = inputs.view(-1)
        dim = 0
    s, _ = torch.max(inputs, dim=dim, keepdim=True) #s是取max值
    outputs = s + (inputs - s).exp().sum(dim=dim, keepdim=True).log() #没看懂？？max+（（x-max）取e，取和，取ln）
    # outputs =inputs.sum(dim=dim, keepdim=True)
    if not keepdim:
        outputs = outputs.squeeze(dim)
    return outputs,s



In [19]:
a=torch.tensor([[1,2,3],[4,5,6]])
print(a)
dim=1
if dim is None:
        a = a.view(-1)
        dim = 0
        print(a)
s,_=torch.max(a,dim=dim,keepdim=True)
print(s)
outputs=(a-s).exp().sum(dim=dim, keepdim=True).log()
print(outputs)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[3],
        [6]])
tensor([[0.4076],
        [0.4076]])
